name: Update Blog List
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-blog-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Ensure full commit history

      - name: Generate Blog List JSON
        run: |
          if [ ! -d "blogs" ]; then
            echo "No blogs directory found, skipping blog list update."
            exit 0
          fi

          echo "[" > blog-list.json

          function sanitize_filename {
            local filename="$1"
            # Convert Turkish characters to ASCII
            filename=$(echo "$filename" | tr 'çğıöşüÇĞİÖŞÜ' 'cgiosuCGIOSU')
            # Remove special characters
            filename=$(echo "$filename" | sed 's/[^a-zA-Z0-9._-]/_/g')
            # Convert to lowercase
            filename=$(echo "$filename" | tr '[:upper:]' '[:lower:]')
            # Shorten filename if too long
            if [ ${#filename} -gt 100 ]; then
              hash=$(echo -n "$filename" | md5sum | cut -c1-8)
              filename="${filename:0:92}_${hash}"
            fi
            echo "$filename"
          }

          for file in blogs/*.html; do
            title=$(grep -o '<title>.*</title>' "$file" | sed 's/<\/\?title>//g')
            upload_date=$(git log --diff-filter=A --follow --format=%aI -- "$file" | tail -1 || true)

            # If no commit history, use the current date
            if [ -z "$upload_date" ]; then
              upload_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            fi

            # Get sanitized filename
            safe_filename=$(sanitize_filename "$file")

            echo "{ \"title\": \"$title\", \"url\": \"$safe_filename\", \"date\": \"$upload_date\" }," >> blog-list.json
          done

          sed -i '$ s/,$//' blog-list.json
          echo "]" >> blog-list.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog-list.json
          git commit -m "Auto-update blog list" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
