name: Update Blog List
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-blog-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate Blog List JSON
        run: |
          echo "[" > blog-list.json
          for file in blogs/*.html; do
            title=$(grep -o '<title>.*</title>' "$file" | sed 's/<\/\?title>//g')
            echo "{ \"title\": \"$title\", \"url\": \"$file\", \"date\": \"$(date -r "$file" +%Y-%m-%d %H:%M)\" }," >> blog-list.json
          done
          sed -i '$ s/,$//' blog-list.json
          echo "]" >> blog-list.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add blog-list.json
          git commit -m "Auto-update blog list" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
